### ISSUE TITLE
Duplicate keys in some specifications

### ISSUE THREAD

**Issue by stillyslalom** [polyanskiy/refractiveindex.info-database#59]
Two CRYSTRAN entries have specifications with duplicate YAML keys. YAML forbids duplicate keys, so these entries fail to load.

https://github.com/polyanskiy/refractiveindex.info-database/blob/307171bc55074a415be0d23183a505dd481b8c34/database/data/specs/crystran/optical/quartz-o.yml#L38-L43

https://github.com/polyanskiy/refractiveindex.info-database/blob/307171bc55074a415be0d23183a505dd481b8c34/database/data/specs/crystran/optical/LaF3-o.yml#L27-L33

**Comment by stillyslalom** [comment]
These could be fixed by either of the following formats:
```
thermal_expansion:
  para:
    temperature: 323
    value: 7.1e-06
  perp:
    temperature: 323
    value: 13.2e-06
```
which produces a dict with two keys, `para` and `perp`, or
```
thermal_expansion:
  - direction: para
    temperature: 323
    value: 7.1e-06
  - direction: perp
    temperature: 323
    value: 13.2e-06
```
which produces a two-element array of dicts with "para" and "perp" as values for the "direction" keys. I have no preference for which is chosen.
