### ISSUE TITLE
Missing coefficient in Bosomworth-80K.yml

### ISSUE THREAD

**Issue by mfschubert** [polyanskiy/refractiveindex.info-database#60]
Hi, it seems like there is a missing coefficient in the Bosomworth-80K.yml file.

It specifies to use dispersion formula #4 ("RefractiveIndex.INFO"), but only provides 8 coefficients. As far as I can tell, this is an invalid number of coefficients for this formula.

![Image](https://github.com/user-attachments/assets/fc47ddb5-c278-44ab-9377-7dbf11df0778)

Below is a snippet from the yml file.

```yaml
REFERENCES: |
    D. R. Bosomworth.
    Far-infrared optical properties of CaF<sub>2</sub>, SrF<sub>2</sub>, BaF<sub>2</sub>, and CdF<sub>2</sub>.
    <a href="https://doi.org/10.1103/PhysRev.157.709"><i>Phys. Rev.</i>, <b>157</b>, 709 (1967)</a>
COMMENTS: |
    80 K
CONDITIONS:
    temperature: 80
DATA:
  - type: formula 4
    wavelength_range: 46.5 999.9
    coefficients: 0 6.04 2 44.444 2 -4088.9 0 44.444
```

Thanks!
